use pest::iterators::{Pair, Pairs};

use crate::{directory::DirFunc};
use crate::{quadruples::Quadruples};
use crate::constants::{DIV, ENTERO_TYPE, ASSIGN, PARENTHESIS, FLOTANTE_TYPE, GLOBAL, MULTP, NULA_TYPE, PLUS, SUBS, LESS, MORE, EQUAL, NOT_EQUAL};

use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "compiler_rules.pest"]
pub struct CSVParser;

pub struct Compiler {
    pub directory : DirFunc,
    pub quads : Quadruples,
}

impl Compiler {
    /// Main function in charge of compiling the whole program step by step
    pub fn compile_program(&mut self, program : &str) -> Result<(), String> {
        let nodes = CSVParser::parse(Rule::PROGRAM, program)
            .map_err(|e| format!("Syntax error: {}", e))?; // ! AI Claude helped me on how to throw syntax error when the parsing fails
        
        self.create_instructions(nodes)?;
        Ok(())
    }

    /// This function in charge of creating an instance when calling ::new()
    pub fn new() -> Self {
        Compiler {
            directory : DirFunc::new(),
            quads : Quadruples::new(),
        }
    }

    /// This function is in charge of created directory of functions and their variables
    
    fn create_instructions(&mut self, nodes : Pairs<Rule>) -> Result<(), String> {
        // ! The AI Claude was prompted to help me understand how to traverse the tree generated by Pest, which is using '.into_inner()'
        
        //* Inside the PROGRAM rule */
        self.directory.create_function(GLOBAL, NULA_TYPE)?; // Creates global function
        //* Reading from the top node PROGRAM */
        for node in nodes { // Returns the single PROGRAM that gives Pairs<Rule>
            for program_child in node.into_inner() {
                match program_child.as_rule() {
                    Rule::VARS => {
                        //* Process variables */
                        self.process_vars(program_child, GLOBAL)?; // Pass VARS? to the next function to process MULT_VARS. In scope global
                    },
                    Rule::FUNCS => {
                        //* Process function by passing the function match */
                        self.processes_function(program_child)?;
                    },
                    Rule::BODY => {
                        //* Process the body by going to its child and passing 'ESTATUTO' */
                        self.quads.current_func = GLOBAL.to_string();
                        self.handle_body(program_child)?;
                    }
                    _ => { }
                }
            }
        }
        Ok(())
    }

    //* **** The next functions help traverse the tree and generate the quadruples */
    /// Process the body
    fn handle_body(&mut self, body : Pair<Rule>) -> Result<(), String> {
        for body_child in body.into_inner() {
            match body_child.as_rule() {
                Rule::ESTATUTO => {
                    self.handle_statute(body_child)?;
                },
                _ => {}
            }
        }
        Ok(())
    }

    /// Processes the 'ESTATUTO' which are the different types of lines that exist in the program
    fn handle_statute(&mut self, statute : Pair<Rule>) -> Result<(), String> {
        //* Iterate over all the different types of statutes */
        for statute_child in statute.into_inner() {
            match statute_child.as_rule() {
                Rule::ASIGNA => {
                    self.handle_assign(statute_child)?;
                },
                Rule::CONDICION => {
                    // Handle rule: CONDICION = {"si" ~ "(" ~ EXPRESION ~ ")" ~ BODY ~ ("sino" ~ BODY)? ~ ";"}
                    self.handle_condition(statute_child)?;
                },
                Rule::CICLO => {
                    //* Handle rule: CICLO = {"mientras" ~ "(" ~ EXPRESION ~ ")" ~ "haz" ~ BODY ~ ";"} */
                    let mut cicle_children = statute_child.into_inner();

                    self.quads.push_jump(); // Save in the jump stack that in here starts the while. To save where the EXPRESION starts
                    let expression = cicle_children.next().unwrap();
                    self.handle_expression(expression)?;
                    self.quads.add_gotof(); // Create a gotoF with the last var of the stack, and saves it in the jump
                    let body = cicle_children.next().unwrap();
                    self.handle_body(body)?;
                    self.quads.add_goto_while(); // Handles updating the gotoF and adding the goto
                },
                Rule::CALL => {},
                Rule::IMPRIME => {},
                Rule::ESTATUTO => {
                    self.handle_statute(statute_child)?;
                },
                _ => {}
            }
        }
        Ok(())
    }

    /// Handle rule: CONDICION = {"si" ~ "(" ~ EXPRESION ~ ")" ~ BODY ~ ("sino" ~ BODY)? ~ ";"}
    pub fn handle_condition(&mut self, condition : Pair<Rule>) -> Result<(), String> {
        let mut condition_children = condition.into_inner();

        let expression = condition_children.next().unwrap();
        self.handle_expression(expression)?;
        self.quads.add_gotof(); // After checking expression, add the false that needs to be checked

        // Processes the body
        let body = condition_children.next().unwrap();
        self.handle_body(body)?;

        // Check if there is an else body
        match condition_children.next() {
            Some(else_body) => {
                self.quads.add_goto_if();
                self.handle_body(else_body)?; // Process the body inside

            },
            None => { // There is no 'ELSE' like statement}  
            }
        }
        self.quads.update_gotox(); // Process the goto or gotoF. Depending on previous match
        Ok(())
    }

    /// Handle rule: ASIGNA = { ID ~ "=" ~ EXPRESION ~ ";" }
    /// Handle assigning statute to add them in the quadruples
    pub fn handle_assign(&mut self, assign : Pair<Rule>) -> Result<(), String> {
        for assing_child in assign.into_inner() {
            match assing_child.as_rule() {
                Rule::ID => {
                    // Save the assign in the stack
                    let var_type = self.directory.get_var_type_of(&self.quads.current_func, assing_child.as_str())?;
                    self.quads.push_var(assing_child.as_str().to_string(), var_type);

                    // Push the assign operator
                    self.quads.push_op(ASSIGN.to_string());
                },
                Rule::EXPRESION => {
                    self.handle_expression(assing_child)?;
                },
                _ => {},
            }
        }

        // Quadruple last operator must be '='
        self.quads.resolve()?;
        Ok(())
    }

    /// Handle rule: EXPRESION = { EXPR ~ (OPERATOR ~ EXPR)? }
    /// Handle expressions handle the *,/,+,-,etc
    pub fn handle_expression(&mut self, expression : Pair<Rule>) -> Result<(), String> {
        //* Iterate over all the expressions */
        for expression_child in expression.into_inner() {
            match expression_child.as_rule() {
                Rule::EXPR => {
                    self.handle_expr(expression_child)?;
                },
                Rule::OPERATOR => {
                    //* Add to the stack a logic operator */
                    self.quads.push_op(expression_child.as_str().to_string());
                },
                _ => {},
            }
        }

        //* Flush any remaining logic operators after processing */
        while let Some(top) = self.quads.stack_op_last() {
            if top == LESS || top == MORE || top == EQUAL || top == NOT_EQUAL {
                self.quads.resolve()?;
            } else { break; }
        }

        Ok(())
    }

    /// Handle the rule: EXPR = { TERM ~ (ARITH_OP ~ TERM)* }
    fn handle_expr(&mut self, expr : Pair<Rule>) -> Result<(), String> {
        for child in expr.into_inner() {
            match child.as_rule() {
                Rule::TERM => {
                    self.handle_term(child)?;
                },
                Rule::ARITH_OP => {
                    //* Before adding the next '+' or '-', resolve the pending ones */
                    if let Some(top) = self.quads.stack_op_last() {
                        if top == PLUS || top == SUBS {
                            self.quads.resolve()?;
                        }
                    }

                    self.quads.push_op(child.as_str().to_string());
                },
                _ => {},
            }
        }
        //* Flush any remaining ARITH_OP operators after processing */
        while let Some(top) = self.quads.stack_op_last() {
            if top == PLUS || top == SUBS {
                self.quads.resolve()?;
            } else { break; }
        }
        Ok(())
    }

    /// Handle the rule: TERM = { FACTOR ~ ( MULT_OP ~ FACTOR)* }
    fn handle_term(&mut self, term : Pair<Rule>) -> Result<(), String> {
        for child in term.into_inner() {
            match child.as_rule() {
                Rule::FACTOR => {
                    self.handle_factor(child)?;
                },
                Rule::MULT_OP => {
                    //* Before adding the next MULT_OP, resolve pending ones */
                    if let Some(top) = self.quads.stack_op_last() {
                        if top == MULTP || top == DIV {
                            self.quads.resolve()?;
                        }
                    }

                    self.quads.push_op(child.as_str().to_string());

                },
                _ => {}
            }
        }
        //* Flush any remaining MULT operators after processing */
        while let Some(top) = self.quads.stack_op_last() {
            if top == MULTP || top == DIV {
                self.quads.resolve()?;
            } else { break; }
        }
        Ok(())
    }

    /// Handle the rule: FACTOR = { SINGLE_EXPR | CALL | SINGLE_FACTOR }
    fn handle_factor(&mut self, factor : Pair<Rule>) -> Result<(), String> {
        let inner = factor.into_inner().next().unwrap(); // Get the first child
        match inner.as_rule() {
            Rule::SINGLE_EXPR => {
                //* SINGLE_EXPR = { "(" ~ EXPRESION ~ ")" } */
                // Push a fake bottom so inner flush loops don't consume outer operators
                self.quads.push_op(PARENTHESIS.to_string());
                let expression = inner.into_inner().next().unwrap();
                self.handle_expression(expression)?;
                self.quads.pop_op(); // Remove the fake bottom after expression resolves
            },
            Rule::CALL => {},
            Rule::SINGLE_FACTOR => {
                // Process single factor, and adds variable to stack
                let single_factor = inner.into_inner();
                self.process_single_factor(single_factor)?;
            },
            _ => {},
        }
        Ok(())
    }

    /// Handles rule: SINGLE_FACTOR = { ARITH_OP? ~ (ID | CTE )}
    /// After getting single factor, gets if it has a sign, gets if is ENTERO or FLOTANTE, and gets if is a CTE or ID
    /// Adds variable to stack 
    fn process_single_factor(&mut self, mut single_factor : Pairs<Rule>) -> Result<(), String> {
        let mut term = single_factor.next().unwrap();
        let var_name;
        // Handle when the ID/CTE has a sign before it
        if term.as_rule() == Rule::ARITH_OP {
            let sign = term.as_str(); // get sign as string
            
            term = single_factor.next().unwrap(); // get the ID or CTE
            var_name = format!("{}{}", sign, term.as_str());
        } else {
            var_name = term.as_str().to_string();
        }

        // Get the type of the CTE/ID
        let mut var_type : String = "".to_string();
        match term.as_rule() {
            Rule::ID => {
                var_type = self.directory.get_var_type_of(&self.quads.current_func, term.as_str())?;

            },
            Rule::CTE => {
                let cte_inner = term.into_inner().next().unwrap(); // Go to next child inside CTE
                
                var_type = match cte_inner.as_rule() {
                    Rule::cte_ent => ENTERO_TYPE.to_string(),
                    Rule::cte_flot => FLOTANTE_TYPE.to_string(),
                    _ => return Err(format!("Invalid constant")),
                }
            },
            _ => {},
        }
        self.quads.push_var(var_name, var_type);
        Ok(())
    }

    //* **** The next functions help build the directory of functions and its variables */
    /// Processes the functions processes
    fn processes_function(&mut self, function : Pair<Rule>) -> Result<(), String> {
        //* Iterate over function statements, and processes its type and its variables */
        let mut funct_type : &str = "";
        let mut function_name : &str = "";

        for func_child in function.into_inner() {
            match func_child.as_rule() {
                Rule::FUNC_TYPE => {
                    funct_type = func_child.as_str();
                },
                Rule::ID => {
                    function_name = func_child.as_str();
                    self.directory.create_function(function_name, funct_type)?;
                }
                Rule::PARAMETERS => {
                    //* Process each SINGLE_VAR that exists in parameters */
                    for params in func_child.into_inner() {
                        let mut var_name  = "";
                        let mut var_type;
                        match params.as_rule() {
                            Rule::SINGLE_VARS => {
                                //* Traverse for each variable, its ID and TYPE  */
                                for var in params.into_inner() {
                                    match  var.as_rule() {
                                        Rule::ID => { var_name = var.as_str(); },
                                        Rule::TYPE => { 
                                            var_type = var.as_str(); 
                                            self.directory.add_variable_to_function(function_name, var_name, var_type)?;
                                        }
                                        _ => {}
                                    }
                                }
                            }
                            _ => {}
                        }
                    }
                },
                Rule::VARS => {
                    self.process_vars(func_child, function_name)?;
                }
                _ => {},
            }
        }
        Ok(())
    }
    

    /// Processes this single argument: MULT_VARS = {ID ~ ("," ~ ID)* ~ ":" ~ TYPE ~ ";"}
    fn process_vars(&mut self, vars : Pair<Rule>, func_name : &str) -> Result<(), String> {
        for mult_var in vars.into_inner() {
            let mut ids : Vec<&str> = Vec::new();
            let mut var_type : &str = "";

            //* Iterate over every statement of MULT_VARS */
            for variables in mult_var.into_inner() {
                match variables.as_rule() {
                    Rule::ID => { ids.push(variables.as_str());},
                    Rule::TYPE => { var_type = variables.as_str()},
                    _ => { }
                }
            }
            
            for id in ids {
                self.directory.add_variable_to_function(func_name, id, var_type)?;
            }
        }
        Ok(())
    }
}


//* Following Rust convention of adding tests inside file tested */
#[cfg(test)]
mod tests {
    use crate::{constants::GOTO, directory::{FuncEntry, VarEntry}, quadruples::Quad};
    use crate::{constants::{GOTOF}};
    use std::{collections::HashMap};
    
    use super::*;  // imports everything from semantic.rs

    fn setup_complex_program() -> Result<Compiler, String> {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa miPrograma;
            vars
                x, y : entero;
                z : flotante;
            flotante function1(id1:entero, sincero:flotante, hola:entero){
                vars
                    var1, x,y : flotante;
                {
                    asignacion = 2 + 4;
                    mientras(true) haz {escribe('hola');};
                }
            };
            inicio
                {
                    x = 5;
                    y = x + 3;
                    si (x > y) {
                        x = x + 1;
                    } sino {
                        y = y + 1;
                    };
                    mientras (x < 10) haz {
                        x = x + 1;
                    };
                    escribe ('resultado:', x);
                }
                fin
            ")?;
        Ok(compiler)
    }

    fn setup_simple_program() -> Result<Compiler, String> {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa miPrograma;
            vars
                x, y : entero;
            flotante function1(id1:entero, sincero:flotante, hola:entero){
                vars
                    var : flotante;
                {
                    mientras(true) haz {escribe('hola');};
                }
            };
            inicio
                { escribe ('resultado:'); }
                fin
            ")?;
        Ok(compiler)
    }

    #[test]
    fn test_valid_quadruples() {
        let program = "
        programa miPrograma;
            vars
                x, y : entero;
            inicio
            { 
                x = (x + 2)*3/(4+7/9);
                y = (((y+x) - y)*3)/4;
                si (x > y) {
                    x = x + 1;
                } sino {
                    y = 3;
                };

                mientras (x) haz {
                    x = 1;
                };
                y = 1;
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let generated_quads = compiler.quads;

        // Build the expected quadruples for expression1
        let mut expected_quads : Quadruples = Quadruples::new();
        expected_quads.quads.push(Quad::new(PLUS.to_string(), "x".to_string(), "2".to_string(),  "t1".to_string()));
        expected_quads.quads.push(Quad::new(MULTP.to_string(),
         "t1".to_string(), "3".to_string(), "t2".to_string()));
        expected_quads.quads.push(Quad::new(DIV.to_string(),
         "7".to_string(), "9".to_string(), "t3".to_string()));
        expected_quads.quads.push(Quad::new(PLUS.to_string(),
         "4".to_string(), "t3".to_string(), "t4".to_string()));
        expected_quads.quads.push(Quad::new(DIV.to_string(),
         "t2".to_string(), "t4".to_string(), "t5".to_string()));
        expected_quads.quads.push(Quad::new(ASSIGN.to_string(),
         "t5".to_string(), "".to_string(), "x".to_string()));

         // Build the expected quadruples for expression2
        expected_quads.quads.push(Quad::new(PLUS.to_string(), "y".to_string(), "x".to_string(),  "t6".to_string()));
        expected_quads.quads.push(Quad::new(SUBS.to_string(),
         "t6".to_string(), "y".to_string(), "t7".to_string()));
        expected_quads.quads.push(Quad::new(MULTP.to_string(),
         "t7".to_string(), "3".to_string(), "t8".to_string()));
        expected_quads.quads.push(Quad::new(DIV.to_string(),
         "t8".to_string(), "4".to_string(), "t9".to_string()));
        expected_quads.quads.push(Quad::new(ASSIGN.to_string(),
         "t9".to_string(), "".to_string(), "y".to_string()));

         // Build expected quadruples for the if statement
         expected_quads.quads.push(Quad::new(MORE.to_string(),
         "x".to_string(), "y".to_string(), "t10".to_string()));
        expected_quads.quads.push(Quad::new(GOTOF.to_string(),
         "t10".to_string(), "".to_string(), "16".to_string()));
        expected_quads.quads.push(Quad::new(PLUS.to_string(), "x".to_string(), "1".to_string(),  "t11".to_string()));
        expected_quads.quads.push(Quad::new(ASSIGN.to_string(), "t11".to_string(), "".to_string(),  "x".to_string()));
        expected_quads.quads.push(Quad::new(GOTO.to_string(), "".to_string(), "".to_string(),  "17".to_string()));
        expected_quads.quads.push(Quad::new(ASSIGN.to_string(), "3".to_string(), "".to_string(),  "y".to_string()));

        // Build expected quadruples for the while
        expected_quads.quads.push(Quad::new(GOTOF.to_string(), "x".to_string(), "".to_string(),  "20".to_string()));
        expected_quads.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(), "".to_string(),  "x".to_string()));
        expected_quads.quads.push(Quad::new(GOTO.to_string(), "".to_string(), "".to_string(),  "17".to_string()));
        expected_quads.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(), "".to_string(),  "y".to_string()));

        assert_eq!(generated_quads.quads, expected_quads.quads);
    }

    #[test]
    fn test_valid_directory() {
        let compiler = setup_complex_program().unwrap();
        
        // check that global function was saved correctly in the directory
        // ! AI Claude helped on knowing how to get values to test if directory is working as expected
        let generated_global_directory = compiler.directory.functions.get(GLOBAL).unwrap();

        // Check for variables in global function
        let expected_global_vars = HashMap::from([
            ("x".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("y".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("z".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_global = FuncEntry::new_with_vars(NULA_TYPE, expected_global_vars);
        
        assert_eq!(generated_global_directory, &correct_global);

        // Check function 1
        let generated_function1_vars = compiler.directory.functions.get("function1").unwrap();

        let function1_vars = HashMap::from([
            ("id1".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("sincero".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
            ("hola".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("var1".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
            ("x".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
            ("y".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let expected_function1_vars = FuncEntry::new_with_vars(FLOTANTE_TYPE, function1_vars);
        
        assert_eq!(generated_function1_vars, &expected_function1_vars);
    }
    
    #[test]
    fn test_invalid_directory() {
        let compiler = setup_simple_program().unwrap();
        
        // check that global function was saved correctly in the directory
        let actual_global = compiler.directory.functions.get(GLOBAL).unwrap();

        // Check for variables in global function
        let global_vars = HashMap::from([
            ("x".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("y".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("z".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_global = FuncEntry::new_with_vars(NULA_TYPE, global_vars);
        
        assert_ne!(actual_global, &correct_global);

        // Check function 1
        let actual_function1 = compiler.directory.functions.get("function1").unwrap();

        let function1_vars = HashMap::from([
            ("id1".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_function1 = FuncEntry::new_with_vars(FLOTANTE_TYPE, function1_vars);
        
        assert_ne!(actual_function1, &correct_function1);
    }

    #[test]
    fn test_valid_program() {
        let result = setup_complex_program();
        assert!(result.is_ok());
    }
    
    #[test]
    fn test_invalid_program() {
        // El error en el siguiente test es debido a que le falta al condicional una llave
        let mut compiler = Compiler::new();
        let program = "
            programa miPrograma;
            vars
                x : entero;
            inicio
                {
                    x = 5;
                    si (x > 3) {
                        x = x + 1;
                    
                }
            fin
            ";
        let result = compiler.compile_program(program);
        assert!(result.is_err());
    }

    // ! The following tests were made with the AI. They take inspiration from previous tests, and generate edge cases to proof test the program

    // ! Following functions tests that the directory of functions is being created correctly
    #[test]
    fn test_directory_single_global_entero() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                a : entero;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL).unwrap();
        let expected_vars = HashMap::from([
            ("a".to_string(), VarEntry::new(ENTERO_TYPE, "")),
        ]);
        assert_eq!(global.vars, expected_vars);
    }

    #[test]
    fn test_directory_single_global_flotante() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                b : flotante;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL).unwrap();
        let expected_vars = HashMap::from([
            ("b".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        assert_eq!(global.vars, expected_vars);
    }

    #[test]
    fn test_directory_multiple_global_same_type() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                a, b, c : entero;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL).unwrap();
        let expected_vars = HashMap::from([
            ("a".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("b".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("c".to_string(), VarEntry::new(ENTERO_TYPE, "")),
        ]);
        assert_eq!(global.vars, expected_vars);
    }

    #[test]
    fn test_directory_global_mixed_types() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                a : entero;
                b : flotante;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL).unwrap();
        assert_eq!(global.vars.get("a").unwrap().var_type, ENTERO_TYPE);
        assert_eq!(global.vars.get("b").unwrap().var_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_global_type_is_nula() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL).unwrap();
        assert_eq!(global.func_type, NULA_TYPE);
    }

    #[test]
    fn test_directory_nula_function_no_params() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula miFuncion() {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("miFuncion").unwrap();
        assert_eq!(func.func_type, "nula");
        assert!(func.vars.is_empty());
    }

    #[test]
    fn test_directory_function_type_flotante() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            flotante calcular() {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("calcular").unwrap();
        assert_eq!(func.func_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_function_type_entero() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            entero obtener() {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("obtener").unwrap();
        assert_eq!(func.func_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_single_param() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula procesar(valor : entero) {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("procesar").unwrap();
        assert_eq!(func.vars.get("valor").unwrap().var_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_multiple_params() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula sumar(a : entero, b : flotante, c : entero) {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("sumar").unwrap();
        assert_eq!(func.vars.get("a").unwrap().var_type, ENTERO_TYPE);
        assert_eq!(func.vars.get("b").unwrap().var_type, FLOTANTE_TYPE);
        assert_eq!(func.vars.get("c").unwrap().var_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_local_vars() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula calcular() {
                vars
                    resultado : flotante;
                    contador : entero;
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("calcular").unwrap();
        assert_eq!(func.vars.get("resultado").unwrap().var_type, FLOTANTE_TYPE);
        assert_eq!(func.vars.get("contador").unwrap().var_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_params_and_local_vars() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            entero procesar(entrada : entero) {
                vars
                    temporal : flotante;
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("procesar").unwrap();
        assert_eq!(func.vars.get("entrada").unwrap().var_type, ENTERO_TYPE);
        assert_eq!(func.vars.get("temporal").unwrap().var_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_multiple_functions() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula funcA() { { } };
            entero funcB() { { } };
            flotante funcC() { { } };
            inicio { }
            fin
        ").unwrap();
        assert!(compiler.directory.functions.contains_key("funcA"));
        assert!(compiler.directory.functions.contains_key("funcB"));
        assert!(compiler.directory.functions.contains_key("funcC"));
        assert_eq!(compiler.directory.functions.get("funcA").unwrap().func_type, "nula");
        assert_eq!(compiler.directory.functions.get("funcB").unwrap().func_type, ENTERO_TYPE);
        assert_eq!(compiler.directory.functions.get("funcC").unwrap().func_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_duplicate_variable_returns_error() {
        let mut compiler = Compiler::new();
        let result = compiler.compile_program("
            programa test;
            vars
                x : entero;
                x : flotante;
            inicio { }
            fin
        ");
        assert!(result.is_err());
    }

    #[test]
    fn test_directory_duplicate_function_returns_error() {
        let mut compiler = Compiler::new();
        let result = compiler.compile_program("
            programa test;
            nula miFuncion() { { } };
            nula miFuncion() { { } };
            inicio { }
            fin
        ");
        assert!(result.is_err());
    }

    // ! Following functions tests that the quadruple are being created correctly

    // --- 'si' only (no else) with logic operators ---

    #[test]
    fn test_quad_if_only_greater() {
        // x = 1;
        // si (x > 5) { x = x + 1; };
        // idx: 0 = 1 _ x
        //      1 > x 5 t1
        //      2 GOTOF t1 _ 5   (false → skip body, end at 5)
        //      3 + x 1 t2
        //      4 = t2 _ x
        let program = "
            programa test;
            vars x : entero;
            inicio {
                x = 1;
                si (x > 5) {
                    x = x + 1;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),  "x".to_string()));
        expected.quads.push(Quad::new(MORE.to_string(),  "x".to_string(),  "5".to_string(), "t1".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(), "t1".to_string(), "".to_string(),  "5".to_string()));
        expected.quads.push(Quad::new(PLUS.to_string(),  "x".to_string(),  "1".to_string(), "t2".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t2".to_string(), "".to_string(),  "x".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_only_less_with_expression_condition() {
        // x = 2;
        // si (x + 3 < 10) { x = 0; };
        // idx: 0 = 2 _ x
        //      1 + x 3 t1
        //      2 < t1 10 t2
        //      3 GOTOF t2 _ 5
        //      4 = 0 _ x
        let program = "
            programa test;
            vars x : entero;
            inicio {
                x = 2;
                si (x + 3 < 10) {
                    x = 0;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "2".to_string(),  "".to_string(),   "x".to_string()));
        expected.quads.push(Quad::new(PLUS.to_string(),  "x".to_string(),  "3".to_string(),  "t1".to_string()));
        expected.quads.push(Quad::new(LESS.to_string(),  "t1".to_string(), "10".to_string(), "t2".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(), "t2".to_string(), "".to_string(),   "5".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),   "x".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_only_equals_two_assignments_in_body() {
        // x = 5; y = 0;
        // si (x == 5) { y = 1; x = 2; };
        // idx: 0 = 5 _ x
        //      1 = 0 _ y
        //      2 == x 5 t1
        //      3 GOTOF t1 _ 6
        //      4 = 1 _ y
        //      5 = 2 _ x
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 5;
                y = 0;
                si (x == 5) {
                    y = 1;
                    x = 2;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "5".to_string(),  "".to_string(),  "x".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "y".to_string()));
        expected.quads.push(Quad::new(EQUAL.to_string(),  "x".to_string(),  "5".to_string(), "t1".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(), "t1".to_string(), "".to_string(),  "6".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),  "y".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "2".to_string(),  "".to_string(),  "x".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_only_not_equal() {
        // x = 7;
        // si (x != 0) { x = x * 2; };
        // idx: 0 = 7 _ x
        //      1 != x 0 t1
        //      2 GOTOF t1 _ 5
        //      3 * x 2 t2
        //      4 = t2 _ x
        let program = "
            programa test;
            vars x : entero;
            inicio {
                x = 7;
                si (x != 0) {
                    x = x * 2;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(),    "7".to_string(),  "".to_string(),  "x".to_string()));
        expected.quads.push(Quad::new(NOT_EQUAL.to_string(), "x".to_string(),  "0".to_string(), "t1".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(),    "t1".to_string(), "".to_string(),  "5".to_string()));
        expected.quads.push(Quad::new(MULTP.to_string(),    "x".to_string(),  "2".to_string(), "t2".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(),    "t2".to_string(), "".to_string(),  "x".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    // --- 'si' / 'sino' (if / else) with logic operators ---

    #[test]
    fn test_quad_if_else_greater() {
        // x = 4; y = 0;
        // si (x > 3) { y = 1; } sino { y = 2; };
        // idx: 0 = 4 _ x
        //      1 = 0 _ y
        //      2 > x 3 t1
        //      3 GOTOF t1 _ 6   (false → else at 6)
        //      4 = 1 _ y        (if body)
        //      5 GOTO _ _ 7     (skip else, end at 7)
        //      6 = 2 _ y        (else body)
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 4;
                y = 0;
                si (x > 3) {
                    y = 1;
                } sino {
                    y = 2;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "4".to_string(),  "".to_string(),  "x".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "y".to_string()));
        expected.quads.push(Quad::new(MORE.to_string(),  "x".to_string(),  "3".to_string(), "t1".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(), "t1".to_string(), "".to_string(),  "6".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),  "y".to_string()));
        expected.quads.push(Quad::new(GOTO.to_string(),  "".to_string(),   "".to_string(),  "7".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "2".to_string(),  "".to_string(),  "y".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_else_less_with_arithmetic_bodies() {
        // x = 1; y = 1;
        // si (x < y) { x = x + y; } sino { x = x - y; };
        // idx: 0 = 1 _ x
        //      1 = 1 _ y
        //      2 < x y t1
        //      3 GOTOF t1 _ 7   (false → else at 7)
        //      4 + x y t2       (if body)
        //      5 = t2 _ x
        //      6 GOTO _ _ 9     (skip else, end at 9)
        //      7 - x y t3       (else body)
        //      8 = t3 _ x
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 1;
                y = 1;
                si (x < y) {
                    x = x + y;
                } sino {
                    x = x - y;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),  "x".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),  "y".to_string()));
        expected.quads.push(Quad::new(LESS.to_string(),  "x".to_string(),  "y".to_string(), "t1".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(), "t1".to_string(), "".to_string(),  "7".to_string()));
        expected.quads.push(Quad::new(PLUS.to_string(),  "x".to_string(),  "y".to_string(), "t2".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t2".to_string(), "".to_string(),  "x".to_string()));
        expected.quads.push(Quad::new(GOTO.to_string(),  "".to_string(),   "".to_string(),  "9".to_string()));
        expected.quads.push(Quad::new(SUBS.to_string(),  "x".to_string(),  "y".to_string(), "t3".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t3".to_string(), "".to_string(),  "x".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_else_equals_with_expression_condition() {
        // x = 6; y = 0;
        // si (x * 2 == 12) { y = 1; } sino { y = 0; };
        // idx: 0 = 6 _ x
        //      1 = 0 _ y
        //      2 * x 2 t1
        //      3 == t1 12 t2
        //      4 GOTOF t2 _ 7   (false → else at 7)
        //      5 = 1 _ y        (if body)
        //      6 GOTO _ _ 8     (skip else, end at 8)
        //      7 = 0 _ y        (else body)
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 6;
                y = 0;
                si (x * 2 == 12) {
                    y = 1;
                } sino {
                    y = 0;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "6".to_string(),  "".to_string(),   "x".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),   "y".to_string()));
        expected.quads.push(Quad::new(MULTP.to_string(), "x".to_string(),  "2".to_string(),  "t1".to_string()));
        expected.quads.push(Quad::new(EQUAL.to_string(),  "t1".to_string(), "12".to_string(), "t2".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(), "t2".to_string(), "".to_string(),   "7".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),   "y".to_string()));
        expected.quads.push(Quad::new(GOTO.to_string(),  "".to_string(),   "".to_string(),   "8".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),   "y".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_else_not_equal_complex_condition() {
        // x = 3; y = 5;
        // si ((x + 1) != (y - 1)) { x = 100; } sino { x = 200; };
        // idx: 0 = 3 _ x
        //      1 = 5 _ y
        //      2 + x 1 t1
        //      3 - y 1 t2
        //      4 != t1 t2 t3
        //      5 GOTOF t3 _ 8   (false → else at 8)
        //      6 = 100 _ x      (if body)
        //      7 GOTO _ _ 9     (skip else, end at 9)
        //      8 = 200 _ x      (else body)
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 3;
                y = 5;
                si ((x + 1) != (y - 1)) {
                    x = 100;
                } sino {
                    x = 200;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(),    "3".to_string(),   "".to_string(),   "x".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(),    "5".to_string(),   "".to_string(),   "y".to_string()));
        expected.quads.push(Quad::new(PLUS.to_string(),     "x".to_string(),   "1".to_string(),  "t1".to_string()));
        expected.quads.push(Quad::new(SUBS.to_string(),     "y".to_string(),   "1".to_string(),  "t2".to_string()));
        expected.quads.push(Quad::new(NOT_EQUAL.to_string(), "t1".to_string(),  "t2".to_string(), "t3".to_string()));
        expected.quads.push(Quad::new(GOTOF.to_string(),    "t3".to_string(),  "".to_string(),   "8".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(),    "100".to_string(), "".to_string(),   "x".to_string()));
        expected.quads.push(Quad::new(GOTO.to_string(),     "".to_string(),    "".to_string(),   "9".to_string()));
        expected.quads.push(Quad::new(ASSIGN.to_string(),    "200".to_string(), "".to_string(),   "x".to_string()));

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    // --- Mixed: assignments + several conditionals together ---

    #[test]
    fn test_quad_two_sequential_ifs() {
        // x = 0; y = 0;
        // si (x < 1) { x = 1; };
        // si (y > 2) { y = 9; } sino { y = 8; };
        // idx: 0 = 0 _ x
        //      1 = 0 _ y
        //      2 < x 1 t1
        //      3 GOTOF t1 _ 6   (first if, no else → end at 6)
        //      4 = 1 _ x
        //      5 (continues)
        //      5 > y 2 t2
        //      6 GOTOF t2 _ 9   (second if, false → else at 9)
        //      7 = 9 _ y        (if body)
        //      8 GOTO _ _ 10    (skip else, end at 10)
        //      9 = 8 _ y        (else body)
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 0;
                y = 0;
                si (x < 1) {
                    x = 1;
                };
                si (y > 2) {
                    y = 9;
                } sino {
                    y = 8;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "x".to_string()));  // 0
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "y".to_string()));  // 1
        expected.quads.push(Quad::new(LESS.to_string(),  "x".to_string(),  "1".to_string(), "t1".to_string())); // 2
        expected.quads.push(Quad::new(GOTOF.to_string(), "t1".to_string(), "".to_string(),  "5".to_string()));  // 3
        expected.quads.push(Quad::new(ASSIGN.to_string(), "1".to_string(),  "".to_string(),  "x".to_string()));  // 4
        expected.quads.push(Quad::new(MORE.to_string(),  "y".to_string(),  "2".to_string(), "t2".to_string())); // 5
        expected.quads.push(Quad::new(GOTOF.to_string(), "t2".to_string(), "".to_string(),  "9".to_string()));  // 6
        expected.quads.push(Quad::new(ASSIGN.to_string(), "9".to_string(),  "".to_string(),  "y".to_string()));  // 7
        expected.quads.push(Quad::new(GOTO.to_string(),  "".to_string(),   "".to_string(),  "10".to_string())); // 8
        expected.quads.push(Quad::new(ASSIGN.to_string(), "8".to_string(),  "".to_string(),  "y".to_string()));  // 9

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_assignments_then_if_else_with_complex_expressions() {
        // x = (1 + 2) * 3;
        // y = x - 4;
        // si (x > y) { x = x + y; } sino { y = x * 2; };
        // idx: 0 + 1 2 t1
        //      1 * t1 3 t2
        //      2 = t2 _ x
        //      3 - x 4 t3
        //      4 = t3 _ y
        //      5 > x y t4
        //      6 GOTOF t4 _ 10  (false → else at 10)
        //      7 + x y t5       (if body)
        //      8 = t5 _ x
        //      9 GOTO _ _ 12    (skip else, end at 12)
        //     10 * x 2 t6       (else body)
        //     11 = t6 _ y
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = (1 + 2) * 3;
                y = x - 4;
                si (x > y) {
                    x = x + y;
                } sino {
                    y = x * 2;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(PLUS.to_string(),  "1".to_string(),  "2".to_string(),  "t1".to_string())); // 0
        expected.quads.push(Quad::new(MULTP.to_string(), "t1".to_string(), "3".to_string(),  "t2".to_string())); // 1
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t2".to_string(), "".to_string(),   "x".to_string()));  // 2
        expected.quads.push(Quad::new(SUBS.to_string(),  "x".to_string(),  "4".to_string(),  "t3".to_string())); // 3
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t3".to_string(), "".to_string(),   "y".to_string()));  // 4
        expected.quads.push(Quad::new(MORE.to_string(),  "x".to_string(),  "y".to_string(),  "t4".to_string())); // 5
        expected.quads.push(Quad::new(GOTOF.to_string(), "t4".to_string(), "".to_string(),   "10".to_string())); // 6
        expected.quads.push(Quad::new(PLUS.to_string(),  "x".to_string(),  "y".to_string(),  "t5".to_string())); // 7
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t5".to_string(), "".to_string(),   "x".to_string()));  // 8
        expected.quads.push(Quad::new(GOTO.to_string(),  "".to_string(),   "".to_string(),   "12".to_string())); // 9
        expected.quads.push(Quad::new(MULTP.to_string(), "x".to_string(),  "2".to_string(),  "t6".to_string())); // 10
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t6".to_string(), "".to_string(),   "y".to_string()));  // 11

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_while_simple() {
        // x = 0;
        // mientras (x < 5) haz { x = x + 1; };
        // idx: 0 = 0 _ x
        //      1 < x 5 t1        (loop start = 1)
        //      2 GOTOF t1 _ 6    (false → exit past loop)
        //      3 + x 1 t2
        //      4 = t2 _ x
        //      5 GOTO _ _ 1      (back to condition)
        let program = "
            programa test;
            vars x : entero;
            inicio {
                x = 0;
                mientras (x < 5) haz {
                    x = x + 1;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "x".to_string()));  // 0
        expected.quads.push(Quad::new(LESS.to_string(),   "x".to_string(),  "5".to_string(), "t1".to_string())); // 1
        expected.quads.push(Quad::new(GOTOF.to_string(),  "t1".to_string(), "".to_string(),  "6".to_string()));  // 2
        expected.quads.push(Quad::new(PLUS.to_string(),   "x".to_string(),  "1".to_string(), "t2".to_string())); // 3
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t2".to_string(), "".to_string(),  "x".to_string()));  // 4
        expected.quads.push(Quad::new(GOTO.to_string(),   "".to_string(),   "".to_string(),  "1".to_string()));  // 5

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_while_big_body() {
        // x = 0; y = 0;
        // mientras (x < 10) haz { x = x + 1; y = y + x; };
        // idx: 0 = 0 _ x
        //      1 = 0 _ y
        //      2 < x 10 t1       (loop start = 2)
        //      3 GOTOF t1 _ 9
        //      4 + x 1 t2
        //      5 = t2 _ x
        //      6 + y x t3
        //      7 = t3 _ y
        //      8 GOTO _ _ 2
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 0;
                y = 0;
                mientras (x < 10) haz {
                    x = x + 1;
                    y = y + x;
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),   "x".to_string()));  // 0
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),   "y".to_string()));  // 1
        expected.quads.push(Quad::new(LESS.to_string(),   "x".to_string(),  "10".to_string(), "t1".to_string())); // 2
        expected.quads.push(Quad::new(GOTOF.to_string(),  "t1".to_string(), "".to_string(),   "9".to_string()));  // 3
        expected.quads.push(Quad::new(PLUS.to_string(),   "x".to_string(),  "1".to_string(),  "t2".to_string())); // 4
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t2".to_string(), "".to_string(),   "x".to_string()));  // 5
        expected.quads.push(Quad::new(PLUS.to_string(),   "y".to_string(),  "x".to_string(),  "t3".to_string())); // 6
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t3".to_string(), "".to_string(),   "y".to_string()));  // 7
        expected.quads.push(Quad::new(GOTO.to_string(),   "".to_string(),   "".to_string(),   "2".to_string()));  // 8

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_while_inside_if() {
        // x = 0;
        // si (x < 3) { mientras (x < 2) haz { x = x + 1; }; };
        // idx: 0 = 0 _ x
        //      1 < x 3 t1        (if condition)
        //      2 GOTOF t1 _ 8    (if false → past if-body, which is the whole while)
        //      3 < x 2 t2        (while condition, loop start = 3)
        //      4 GOTOF t2 _ 8    (while false → exit past loop)
        //      5 + x 1 t3
        //      6 = t3 _ x
        //      7 GOTO _ _ 3      (while back to condition)
        let program = "
            programa test;
            vars x : entero;
            inicio {
                x = 0;
                si (x < 3) {
                    mientras (x < 2) haz {
                        x = x + 1;
                    };
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "x".to_string()));  // 0
        expected.quads.push(Quad::new(LESS.to_string(),   "x".to_string(),  "3".to_string(), "t1".to_string())); // 1
        expected.quads.push(Quad::new(GOTOF.to_string(),  "t1".to_string(), "".to_string(),  "8".to_string()));  // 2
        expected.quads.push(Quad::new(LESS.to_string(),   "x".to_string(),  "2".to_string(), "t2".to_string())); // 3
        expected.quads.push(Quad::new(GOTOF.to_string(),  "t2".to_string(), "".to_string(),  "8".to_string()));  // 4
        expected.quads.push(Quad::new(PLUS.to_string(),   "x".to_string(),  "1".to_string(), "t3".to_string())); // 5
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t3".to_string(), "".to_string(),  "x".to_string()));  // 6
        expected.quads.push(Quad::new(GOTO.to_string(),   "".to_string(),   "".to_string(),  "3".to_string()));  // 7

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_if_else_inside_while() {
        // x = 0;
        // mientras (x < 4) haz {
        //     si (x == 2) { x = x + 10; } sino { x = x + 1; };
        // };
        // idx: 0 = 0 _ x
        //      1 < x 4 t1        (while condition, loop start = 1)
        //      2 GOTOF t1 _ 11   (while exit)
        //      3 == x 2 t2       (if condition)
        //      4 GOTOF t2 _ 8    (if false → else at 8)
        //      5 + x 10 t3       (if body)
        //      6 = t3 _ x
        //      7 GOTO _ _ 10     (skip else → end of if/else = 10)
        //      8 + x 1 t4        (else body)
        //      9 = t4 _ x
        //     10 GOTO _ _ 1      (while back-edge)
        let program = "
            programa test;
            vars x : entero;
            inicio {
                x = 0;
                mientras (x < 4) haz {
                    si (x == 2) {
                        x = x + 10;
                    } sino {
                        x = x + 1;
                    };
                };
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(), "0".to_string(),  "".to_string(),  "x".to_string()));  // 0
        expected.quads.push(Quad::new(LESS.to_string(),   "x".to_string(),  "4".to_string(), "t1".to_string())); // 1
        expected.quads.push(Quad::new(GOTOF.to_string(),  "t1".to_string(), "".to_string(),  "11".to_string())); // 2
        expected.quads.push(Quad::new(EQUAL.to_string(),   "x".to_string(),  "2".to_string(), "t2".to_string())); // 3
        expected.quads.push(Quad::new(GOTOF.to_string(),  "t2".to_string(), "".to_string(),  "8".to_string()));  // 4
        expected.quads.push(Quad::new(PLUS.to_string(),   "x".to_string(),  "10".to_string(),"t3".to_string())); // 5
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t3".to_string(), "".to_string(),  "x".to_string()));  // 6
        expected.quads.push(Quad::new(GOTO.to_string(),   "".to_string(),   "".to_string(),  "10".to_string())); // 7
        expected.quads.push(Quad::new(PLUS.to_string(),   "x".to_string(),  "1".to_string(), "t4".to_string())); // 8
        expected.quads.push(Quad::new(ASSIGN.to_string(), "t4".to_string(), "".to_string(),  "x".to_string()));  // 9
        expected.quads.push(Quad::new(GOTO.to_string(),   "".to_string(),   "".to_string(),  "1".to_string()));  // 10

        assert_eq!(compiler.quads.quads, expected.quads);
    }

    #[test]
    fn test_quad_two_sequential_whiles() {
        // x = 0; y = 0;
        // mientras (x < 2) haz { x = x + 1; };
        // mientras (y != 3) haz { y = y + 1; };
        // x = 99;
        // idx: 0 = 0 _ x
        //      1 = 0 _ y
        //      2 < x 2 t1        (while1 start = 2)
        //      3 GOTOF t1 _ 7
        //      4 + x 1 t2
        //      5 = t2 _ x
        //      6 GOTO _ _ 2
        //      7 != y 3 t3       (while2 start = 7)
        //      8 GOTOF t3 _ 12
        //      9 + y 1 t4
        //     10 = t4 _ y
        //     11 GOTO _ _ 7
        //     12 = 99 _ x
        let program = "
            programa test;
            vars x, y : entero;
            inicio {
                x = 0;
                y = 0;
                mientras (x < 2) haz {
                    x = x + 1;
                };
                mientras (y != 3) haz {
                    y = y + 1;
                };
                x = 99;
            }
            fin
        ";
        let mut compiler = Compiler::new();
        compiler.compile_program(program).unwrap();

        let mut expected = Quadruples::new();
        expected.quads.push(Quad::new(ASSIGN.to_string(),   "0".to_string(),  "".to_string(),  "x".to_string()));  // 0
        expected.quads.push(Quad::new(ASSIGN.to_string(),   "0".to_string(),  "".to_string(),  "y".to_string()));  // 1
        expected.quads.push(Quad::new(LESS.to_string(),     "x".to_string(),  "2".to_string(), "t1".to_string())); // 2
        expected.quads.push(Quad::new(GOTOF.to_string(),    "t1".to_string(), "".to_string(),  "7".to_string()));  // 3
        expected.quads.push(Quad::new(PLUS.to_string(),     "x".to_string(),  "1".to_string(), "t2".to_string())); // 4
        expected.quads.push(Quad::new(ASSIGN.to_string(),   "t2".to_string(), "".to_string(),  "x".to_string()));  // 5
        expected.quads.push(Quad::new(GOTO.to_string(),     "".to_string(),   "".to_string(),  "2".to_string()));  // 6
        expected.quads.push(Quad::new(NOT_EQUAL.to_string(), "y".to_string(),  "3".to_string(), "t3".to_string())); // 7
        expected.quads.push(Quad::new(GOTOF.to_string(),    "t3".to_string(), "".to_string(),  "12".to_string())); // 8
        expected.quads.push(Quad::new(PLUS.to_string(),     "y".to_string(),  "1".to_string(), "t4".to_string())); // 9
        expected.quads.push(Quad::new(ASSIGN.to_string(),   "t4".to_string(), "".to_string(),  "y".to_string()));  // 10
        expected.quads.push(Quad::new(GOTO.to_string(),     "".to_string(),   "".to_string(),  "7".to_string()));  // 11
        expected.quads.push(Quad::new(ASSIGN.to_string(),   "99".to_string(), "".to_string(),  "x".to_string()));  // 12

        assert_eq!(compiler.quads.quads, expected.quads);
    }
}