use std::{collections::HashMap};
use pest::iterators::{Pair, Pairs};

use crate::{dir_func::DirFunc};
use crate::constants::{GLOBAL_SCOPE, NULA_TYPE, ENTERO_TYPE, FLOTANTE_TYPE};

use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "compiler_rules.pest"]
pub struct CSVParser;

pub struct Compiler {
    pub directory : DirFunc,
}

impl Compiler {
    /// Main function in charge of compiling the whole program step by step
    pub fn compile_program(&mut self, program : &str) -> Result<(), String> {
        let nodes = CSVParser::parse(Rule::PROGRAM, program)
            .map_err(|e| format!("Syntax error: {}", e))?; // ! AI Claude helped me on how to throw syntax error when the parsing fails
        
        self.create_dir_function(nodes)?;
        Ok(())
    }

    /// This function in charge of creating an instance when calling ::new()
    pub fn new() -> Self {
        Compiler {
            directory : DirFunc::new(),
        }
    }

    /// Returns the result type of an operation given two types and an operand
    fn obtain_type(left_type : &str, right_type : &str, operand : &str) -> &'static str {
        let type_index: HashMap<&str, usize> = HashMap::from([
        (ENTERO_TYPE,   0),
        (FLOTANTE_TYPE, 1),
        ]);

        let op_index: HashMap<&str, usize> = HashMap::from([
            ("+",  0), ("-",  1), ("*",  2), ("/",  3),
            (">",  4), ("<",  5), ("!=", 6), ("==", 7),
        ]);

        // This semantic cube is a 2x2x8 which matches the types and operands
        static SEMANTIC_CUBE : [[[&str; 8]; 2]; 2] = [
            // left = entero
            [
                // right = entero
                [ENTERO_TYPE,   ENTERO_TYPE,   ENTERO_TYPE,   ENTERO_TYPE,   ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE],
                // right = flotante
                [FLOTANTE_TYPE, FLOTANTE_TYPE, FLOTANTE_TYPE, FLOTANTE_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE],
            ],
            // left = flotante
            [
                // right = entero
                [FLOTANTE_TYPE, FLOTANTE_TYPE, FLOTANTE_TYPE, FLOTANTE_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE],
                // right = flotante
                [FLOTANTE_TYPE, FLOTANTE_TYPE, FLOTANTE_TYPE, FLOTANTE_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE, ENTERO_TYPE],
            ],
        ];

        let left_indx : usize = match type_index.get(left_type) {
            Some(&val) => val, // de-reference the value with &
            None => return "Invalid type", // Ends early the whole function
        };
        let right_indx : usize = match type_index.get(right_type) {
            Some(&val) => val,
            None => return "Invalid type",
        };
        let operand_indx : usize  = match op_index.get(operand) {
            Some(&val) => val,
            None => return "Invalid type",
        };

        return SEMANTIC_CUBE[left_indx][right_indx][operand_indx];
    }

    /// This function is in charge of created directory of functions and their variables
    
    fn create_dir_function(&mut self, nodes : Pairs<Rule>) -> Result<(), String> {
        // ! The AI Claude was prompted to help me understand how to traverse the tree generated by Pest, which is using '.into_inner()'
        
        //* Inside the PROGRAM rule */
        self.directory.create_function(GLOBAL_SCOPE, NULA_TYPE)?; // Creates global function
        //* Reading from the top node PROGRAM */
        for node in nodes {
            for child in node.into_inner() {
                match child.as_rule() {
                    Rule::VARS => {
                        //* Process variables */
                        self.process_vars(child, GLOBAL_SCOPE)?; // Pass VARS? to the next function to process MULT_VARS. In scope global
                    },
                    Rule::FUNCS => {
                        //* Process function by passing the function match */
                        self.processes_function(child)?;
                    },
                    _case => { }
                }
            }
        }
        Ok(())
    }

    //* Next functions are to help to process inner childs of multiple functions */
    
    /// Processes the functions processes
    fn processes_function(&mut self, function : Pair<Rule>) -> Result<(), String> {
        //* Iterate over function statements, and processes its type and its variables */
        let mut funct_type : &str = "";
        let mut function_name : &str = "";

        for func_child
         in function.into_inner() {
            match func_child.as_rule() {
                Rule::FUNC_TYPE => {
                    funct_type = func_child.as_str();
                },
                Rule::ID => {
                    function_name = func_child.as_str();
                    self.directory.create_function(function_name, funct_type)?;
                }
                Rule::PARAMETERS => {
                    //* Process each SINGLE_VAR that exists in parameters */
                    for params in func_child.into_inner() {
                        let mut var_name  = "";
                        let mut var_type;
                        match params.as_rule() {
                            Rule::SINGLE_VARS => {
                                //* Traverse for each variable, its ID and TYPE  */
                                for var in params.into_inner() {
                                    match  var.as_rule() {
                                        Rule::ID => { var_name = var.as_str(); },
                                        Rule::TYPE => { 
                                            var_type = var.as_str(); 
                                            self.directory.add_variable_to_function(function_name, var_name, var_type)?;
                                        }
                                        _case => {}
                                    }
                                }
                            }
                            _case => {}
                        }
                    }
                },
                Rule::VARS => {
                    self.process_vars(func_child, function_name)?;
                }
                _case => {},
            }
        }
        Ok(())
    }
    

    /// Processes this single argument: MULT_VARS = {ID ~ ("," ~ ID)* ~ ":" ~ TYPE ~ ";"}
    fn process_vars(&mut self, vars : Pair<Rule>, func_name : &str) -> Result<(), String> {
        for mult_var in vars.into_inner() {
            let mut ids : Vec<&str> = Vec::new();
            let mut var_type : &str = "";

            //* Iterate over every statement of MULT_VARS */
            for variables in mult_var.into_inner() {
                match variables.as_rule() {
                    Rule::ID => { ids.push(variables.as_str());},
                    Rule::TYPE => { var_type = variables.as_str()},
                    _case => { }
                }
            }
            
            for id in ids {
                self.directory.add_variable_to_function(func_name, id, var_type)?;
            }
        }
        Ok(())
    }
}


//* Following Rust convention of adding tests inside file tested */
#[cfg(test)]
mod tests {
    use crate::dir_func::{FuncEntry, VarEntry};

// ! Claude AI helped me on knowing how to test this file
    use super::*;  // imports everything from semantic.rs

    fn setup_complex_program() -> Result<Compiler, String> {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa miPrograma;
            vars
                x, y : entero;
                z : flotante;
            flotante function1(id1:entero, sincero:flotante, hola:entero){
                vars
                    var1, x,y : flotante;
                {
                    asignacion = 2 + 4;
                    mientras(true) haz {escribe('hola');};
                }
            };
            inicio
                {
                    x = 5;
                    y = x + 3;
                    si (x > y) {
                        x = x + 1;
                    } sino {
                        y = y + 1;
                    };
                    mientras (x < 10) haz {
                        x = x + 1;
                    };
                    escribe ('resultado:', x);
                }
                fin
            ")?;
        Ok(compiler)
    }

    fn setup_simple_program() -> Result<Compiler, String> {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa miPrograma;
            vars
                x, y : entero;
            flotante function1(id1:entero, sincero:flotante, hola:entero){
                vars
                    var : flotante;
                {
                    mientras(true) haz {escribe('hola');};
                }
            };
            inicio
                { escribe ('resultado:'); }
                fin
            ")?;
        Ok(compiler)
    }

    #[test]
    fn test_valid_directory() {
        let compiler = setup_complex_program().unwrap();
        
        // check that global function was saved correctly in the directory
        // ! AI Claude helped on knowing how to get values to test if directory is working as expected
        let actual_global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();

        // Check for variables in global function
        let global_vars = HashMap::from([
            ("x".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("y".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("z".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_global = FuncEntry::new_with_vars(NULA_TYPE, global_vars);
        
        assert_eq!(actual_global, &correct_global);

        // Check function 1
        let actual_function1 = compiler.directory.functions.get("function1").unwrap();

        let function1_vars = HashMap::from([
            ("id1".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("sincero".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
            ("hola".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("var1".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
            ("x".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
            ("y".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_function1 = FuncEntry::new_with_vars(FLOTANTE_TYPE, function1_vars);
        
        assert_eq!(actual_function1, &correct_function1);
    }
    
    #[test]
    fn test_invalid_directory() {
        let compiler = setup_simple_program().unwrap();
        
        // check that global function was saved correctly in the directory
        let actual_global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();

        // Check for variables in global function
        let global_vars = HashMap::from([
            ("x".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("y".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("z".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_global = FuncEntry::new_with_vars(NULA_TYPE, global_vars);
        
        assert_ne!(actual_global, &correct_global);

        // Check function 1
        let actual_function1 = compiler.directory.functions.get("function1").unwrap();

        let function1_vars = HashMap::from([
            ("id1".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        let correct_function1 = FuncEntry::new_with_vars(FLOTANTE_TYPE, function1_vars);
        
        assert_ne!(actual_function1, &correct_function1);
    }

    #[test]
    fn test_valid_program() {
        let result = setup_complex_program();
        assert!(result.is_ok());
    }
    
    #[test]
    fn test_invalid_program() {
        // El error en el siguiente test es debido a que le falta al condicional una llave
        let mut compiler = Compiler::new();
        let program = "
            programa miPrograma;
            vars
                x : entero;
            inicio
                {
                    x = 5;
                    si (x > 3) {
                        x = x + 1;
                    
                }
            fin
            ";
        let result = compiler.compile_program(program);
        assert!(result.is_err());
    }

    // ! The following tests were made with the AI. They take inspiration from previous tests, and generate edge cases to proof test the program

    // ! This tests that the directory is being created correctly
    #[test]
    fn test_directory_single_global_entero() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                a : entero;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();
        let expected_vars = HashMap::from([
            ("a".to_string(), VarEntry::new(ENTERO_TYPE, "")),
        ]);
        assert_eq!(global.vars, expected_vars);
    }

    #[test]
    fn test_directory_single_global_flotante() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                b : flotante;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();
        let expected_vars = HashMap::from([
            ("b".to_string(), VarEntry::new(FLOTANTE_TYPE, "")),
        ]);
        assert_eq!(global.vars, expected_vars);
    }

    #[test]
    fn test_directory_multiple_global_same_type() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                a, b, c : entero;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();
        let expected_vars = HashMap::from([
            ("a".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("b".to_string(), VarEntry::new(ENTERO_TYPE, "")),
            ("c".to_string(), VarEntry::new(ENTERO_TYPE, "")),
        ]);
        assert_eq!(global.vars, expected_vars);
    }

    #[test]
    fn test_directory_global_mixed_types() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            vars
                a : entero;
                b : flotante;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();
        assert_eq!(global.vars.get("a").unwrap().var_type, ENTERO_TYPE);
        assert_eq!(global.vars.get("b").unwrap().var_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_global_type_is_nula() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            inicio { }
            fin
        ").unwrap();
        let global = compiler.directory.functions.get(GLOBAL_SCOPE).unwrap();
        assert_eq!(global.func_type, NULA_TYPE);
    }

    #[test]
    fn test_directory_nula_function_no_params() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula miFuncion() {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("miFuncion").unwrap();
        assert_eq!(func.func_type, "nula");
        assert!(func.vars.is_empty());
    }

    #[test]
    fn test_directory_function_type_flotante() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            flotante calcular() {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("calcular").unwrap();
        assert_eq!(func.func_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_function_type_entero() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            entero obtener() {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("obtener").unwrap();
        assert_eq!(func.func_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_single_param() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula procesar(valor : entero) {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("procesar").unwrap();
        assert_eq!(func.vars.get("valor").unwrap().var_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_multiple_params() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula sumar(a : entero, b : flotante, c : entero) {
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("sumar").unwrap();
        assert_eq!(func.vars.get("a").unwrap().var_type, ENTERO_TYPE);
        assert_eq!(func.vars.get("b").unwrap().var_type, FLOTANTE_TYPE);
        assert_eq!(func.vars.get("c").unwrap().var_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_local_vars() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula calcular() {
                vars
                    resultado : flotante;
                    contador : entero;
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("calcular").unwrap();
        assert_eq!(func.vars.get("resultado").unwrap().var_type, FLOTANTE_TYPE);
        assert_eq!(func.vars.get("contador").unwrap().var_type, ENTERO_TYPE);
    }

    #[test]
    fn test_directory_function_params_and_local_vars() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            entero procesar(entrada : entero) {
                vars
                    temporal : flotante;
                { }
            };
            inicio { }
            fin
        ").unwrap();
        let func = compiler.directory.functions.get("procesar").unwrap();
        assert_eq!(func.vars.get("entrada").unwrap().var_type, ENTERO_TYPE);
        assert_eq!(func.vars.get("temporal").unwrap().var_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_multiple_functions() {
        let mut compiler = Compiler::new();
        compiler.compile_program("
            programa test;
            nula funcA() { { } };
            entero funcB() { { } };
            flotante funcC() { { } };
            inicio { }
            fin
        ").unwrap();
        assert!(compiler.directory.functions.contains_key("funcA"));
        assert!(compiler.directory.functions.contains_key("funcB"));
        assert!(compiler.directory.functions.contains_key("funcC"));
        assert_eq!(compiler.directory.functions.get("funcA").unwrap().func_type, "nula");
        assert_eq!(compiler.directory.functions.get("funcB").unwrap().func_type, ENTERO_TYPE);
        assert_eq!(compiler.directory.functions.get("funcC").unwrap().func_type, FLOTANTE_TYPE);
    }

    #[test]
    fn test_directory_duplicate_variable_returns_error() {
        let mut compiler = Compiler::new();
        let result = compiler.compile_program("
            programa test;
            vars
                x : entero;
                x : flotante;
            inicio { }
            fin
        ");
        assert!(result.is_err());
    }

    #[test]
    fn test_directory_duplicate_function_returns_error() {
        let mut compiler = Compiler::new();
        let result = compiler.compile_program("
            programa test;
            nula miFuncion() { { } };
            nula miFuncion() { { } };
            inicio { }
            fin
        ");
        assert!(result.is_err());
    }
}